---
- hosts: localhost

  vars_prompt:

    - name: username
      prompt: "Enter your student number "
      private: no

    - name: password
      prompt: "Enter your student password "
      unsafe: yes
      private: no

  vars:

    secret: '/kv/{{ username }}'

  tasks:

    - hashivault_status:
      register: 'vault_status'

    - hashivault_write:
        secret: '{{ secret }}'
        data:
            username: '{{ username }}'
            password: '{{ password }}'
      register: 'vault_write'

    - hashivault_read:
        secret: '{{ secret }}'
        key: "{{ item }}"
      loop:
        - username
        - password
      register: 'vault_read'
