---
- hosts: localhost
  become: yes
  ignore_errors: yes

  tasks:
  - name: stop vault service
    command: 'systemctl stop vault.service'

  - name: delete vault binary
    file: 
      path: /usr/local/bin/vault
      state: absent

  - name: delete systemctl file
    file: 
      path: /etc/systemd/system/vault.service
      state: absent
 
  - name: reload systemctl daemon
    command: 'systemctl daemon-reload'

  - name: delete tmp files
    file: 
      path: /tmp/vault
      state: absent

  - name: remove rootkey
    file:
      path: rootKey
      state: absent

  - name: remove seal key
    file:
      path: unsealKey
      state: absent


